services:
  mysqldb:
    image: mysql
    container_name: medilabo-mysql
    ports:
      - 3308:3308
    expose:
      - 3308
    volumes:
      - ./patient.sql:/docker-entrypoint-initdb.d/patient.sql
    networks:
      - medilabo-network
    environment:
      MYSQL_DATABASE: patient
      MYSQL_USER: user1
      MYSQL_PASSWORD: passer123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      timeout: 20s
      retries: 5

  mongodb:
    image: mongo
    container_name: medilabo-mongo
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - medilabo-network

  gateway-service:
    build: ./ms-gateway
    container_name: medilabo-gateway
    restart: always
    ports:
      - 8080:8080
    networks:
      - medilabo-network
    depends_on:
      - mysqldb
      - mongodb

  front-ui:
    build: ./ms-front
    container_name: medilabo-front-ui
    restart: always
    ports:
      - 8081:8081
    networks:
      - medilabo-network
    depends_on:
      gateway-service:
        condition: service_started

  patient-service:
    build: ./ms-patient
    container_name: medilabo-patient
    restart: always
    ports:
      - 8082:8082
    networks:
      - medilabo-network
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: user1
      MYSQL_PASSWORD: passer123
      MYSQL_PORT: 3308
    depends_on:
      mysqldb:
        condition: service_started
      gateway-service:
        condition: service_started

  note-service:
    build: ./ms-note
    container_name: medilabo-note
    restart: always
    ports:
      - 8083:8083
    networks:
      - medilabo-network
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
    depends_on:
      mongodb:
        condition: service_started
      gateway-service:
        condition: service_started
        
  evaluation-service:
    build: ./ms-evaluation
    container_name: medilabo-evaluation
    restart: always
    ports:
      - 8084:8084
    networks:
      - medilabo-network
    depends_on:
      gateway-service:
        condition: service_started
        
  auth-service:
    build: ./ms-authentication
    container_name: medilabo-auth
    restart: always
    ports:
      - 8085:8085
    networks:
      - medilabo-network
    depends_on:
      gateway-service:
        condition: service_started

    volumes:
      - .m2:/root/.m2

networks:
  medilabo-network: