services:
  mysqldb:
    image: mysql
    container_name: medilabo-mysql
    ports:
      - 3308:3308
    volumes:
      - ./patient.sql:/docker-entrypoint-initdb.d/patient.sql
    networks:
      - medilabo-network
    environment:
      MYSQL_DATABASE: patient
      MYSQL_USER: user1
      MYSQL_PASSWORD: passer123
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      timeout: 20s
      retries: 5

  mongodb:
    image: mongo
    container_name: medilabo-mongo
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - medilabo-network

  gateway-service:
    build: ./ms-gateway
    container_name: medilabo-gateway
    restart: always
    ports:
      - 8080:8080
    networks:
      - medilabo-network
    depends_on:
      - mysqldb
      - mongodb

  patient-service:
    build: ./ms-patient
    container_name: medilabo-patient
    restart: always
    ports:
      - 8082:8082
    networks:
      - medilabo-network
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: user1
      MYSQL_PASSWORD: passer123
      MYSQL_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy
      gateway-service:
        condition: service_started

  note-service:
    build: ./ms-note
    container_name: medilabo-note
    restart: always
    ports:
      - 8083:8083
    networks:
      - medilabo-network
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
    depends_on:
      mongodb:
        condition: service_started
      gateway-service:
        condition: service_started

    volumes:
      - .m2:/root/.m2

networks:
  medilabo-network: